### ISSUE TITLE
Erro ao executar

### ISSUE THREAD

**Issue by viniciusccosta** [viniciusccosta/PFX-Expiration#1]
O seguinte erro está acontecendo ao tentar executar o programa:

```
Traceback (most recent call last):
  File "app.py", line 193, in <module>
  File "app.py", line 161, in get_certificados
ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by viniciusccosta** [comment]
O erro aconteceu devido a 2 certificados que foram instalados juntamente com o "Microsoft Your Phone".
Ao listar os certificados, eles não seguem o mesmo padrão dos outros certificados, em especial no requerente e isso estava causando o erro.

```
Número de Série: 4***********eebf
Emissor: CN=2ab1****-****-****-****-********6442
 NotBefore: 13/09/2023 07:45
 NotAfter: 12/09/2024 19:45
Requerente: CN=2a******-****-****-****-********6442
Assinatura coincide com Chave pública
Certificado raiz: requerente coincide com o emissor
Hash Cert(sha1): 3f************************************45
  Contêiner da chave = af84****-****-****-****-********6ab0
  Nome de contêiner exclusivo: 68****************************33_********-****-****-****-********8d3f
  Provider = Microsoft Software Key Storage Provider
A chave privada NÃO é exportável
Teste de assinatura aprovado
```
